insert into PUBLIC.CARD_CUSTOMER (CARD_CUSTOMER_ID, TYPE, EXPIRY_DATE, LIMIT, CUSTOMER_ID, ISDEBIT) values (1, 'Visa', '2020-09-16', 2000, 1, 'true');
insert into PUBLIC.CARD_CUSTOMER (CARD_CUSTOMER_ID, TYPE, EXPIRY_DATE, LIMIT, CUSTOMER_ID, ISDEBIT) values (2, 'maestro', '2021-09-17', 3000, 2, 'false');
insert into PUBLIC.CARD_CUSTOMER (CARD_CUSTOMER_ID, TYPE, EXPIRY_DATE, LIMIT, CUSTOMER_ID, ISDEBIT) values (3, 'mastercard', '2022-09-22', 1000, 3, 'true');
insert into PUBLIC.CARD_CUSTOMER (CARD_CUSTOMER_ID, TYPE, EXPIRY_DATE, LIMIT, CUSTOMER_ID, ISDEBIT) values (4, 'visa', '2023-09-27', 4000, 4, null);
insert into PUBLIC.CARD_CUSTOMER (CARD_CUSTOMER_ID, TYPE, EXPIRY_DATE, LIMIT, CUSTOMER_ID, ISDEBIT) values (5, 'visa', '2023-09-08', 3000, 1, 'false');
