insert into PUBLIC.ADDRESS_CUSTOMER (ADDRESS_CUSTOMER_ID, CUSTOMER_ID, ADDRESS_ID) values (1, 1, 1);
insert into PUBLIC.ADDRESS_CUSTOMER (ADDRESS_CUSTOMER_ID, CUSTOMER_ID, ADDRESS_ID) values (2, 2, 2);
insert into PUBLIC.ADDRESS_CUSTOMER (ADDRESS_CUSTOMER_ID, CUSTOMER_ID, ADDRESS_ID) values (3, 3, 3);
insert into PUBLIC.ADDRESS_CUSTOMER (ADDRESS_CUSTOMER_ID, CUSTOMER_ID, ADDRESS_ID) values (4, 4, 4);
insert into PUBLIC.ADDRESS_CUSTOMER (ADDRESS_CUSTOMER_ID, CUSTOMER_ID, ADDRESS_ID) values (5, 1, 3);
insert into PUBLIC.ADDRESS_CUSTOMER (ADDRESS_CUSTOMER_ID, CUSTOMER_ID, ADDRESS_ID) values (8, 12345, 9);
insert into PUBLIC.ADDRESS_CUSTOMER (ADDRESS_CUSTOMER_ID, CUSTOMER_ID, ADDRESS_ID) values (9, 485023412, 10);
