package org.db;


public class QueryHelper {
    public static final String CUSTOMER_TABLE_REGISTRATION = "INSERT INTO CUSTOMER(CUST_NAME, CUST_LASTNAME, GENDER, NATIONALITY, BIRTHDATE, DATE_BECAME_CUSTOMER, OTHER_DETAIL) VALUES(";
}
